/**
 * Error code definitions
 */

export const ERROR_CODES = {
  // Authentication (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_TOKEN_INVALID: 'AUTH_004',

  // Authorization (AUTHZ_xxx)
  AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_001',
  AUTHZ_TIER_REQUIRED: 'AUTHZ_002',

  // Validation (VAL_xxx)
  VAL_INVALID_INPUT: 'VAL_001',
  VAL_MISSING_REQUIRED_FIELD: 'VAL_002',
  VAL_INVALID_FORMAT: 'VAL_003',

  // Rate Limiting (RATE_xxx)
  RATE_LIMIT_EXCEEDED: 'RATE_001',
  RATE_DAILY_LIMIT_REACHED: 'RATE_002',

  // Payment (PAY_xxx)
  PAY_PAYMENT_FAILED: 'PAY_001',
  PAY_SUBSCRIPTION_INACTIVE: 'PAY_002',
  PAY_INVALID_TIER: 'PAY_003',

  // Game (GAME_xxx)
  GAME_INVALID_DIFFICULTY: 'GAME_001',
  GAME_THEME_NOT_AVAILABLE: 'GAME_002',
  GAME_ALREADY_COMPLETED: 'GAME_003',

  // Not Found (NF_xxx)
  NF_USER_NOT_FOUND: 'NF_001',
  NF_GAME_NOT_FOUND: 'NF_002',
  NF_THEME_NOT_FOUND: 'NF_003',
  NF_SUBSCRIPTION_NOT_FOUND: 'NF_004',

  // Server (SRV_xxx)
  SRV_INTERNAL_ERROR: 'SRV_001',
  SRV_SERVICE_UNAVAILABLE: 'SRV_002',
} as const;
