include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Keep the scaffold pragmatic; tighten later.
    avoid_print: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    always_declare_return_types: true
